// @generated by protoc-gen-es v1.10.1
// @generated from file order.proto (package order, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum order.OrderStatus
 */
export declare enum OrderStatus {
  /**
   * @generated from enum value: ORDER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORDER_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: ORDER_STATUS_CONFIRMED = 2;
   */
  CONFIRMED = 2,

  /**
   * @generated from enum value: ORDER_STATUS_SHIPPED = 3;
   */
  SHIPPED = 3,

  /**
   * @generated from enum value: ORDER_STATUS_DELIVERED = 4;
   */
  DELIVERED = 4,

  /**
   * @generated from enum value: ORDER_STATUS_CANCELLED = 5;
   */
  CANCELLED = 5,
}

/**
 * @generated from message order.Order
 */
export declare class Order extends Message<Order> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string customer_id = 2;
   */
  customerId: string;

  /**
   * @generated from field: repeated order.OrderItem items = 3;
   */
  items: OrderItem[];

  /**
   * @generated from field: double total_price = 4;
   */
  totalPrice: number;

  /**
   * @generated from field: order.OrderStatus status = 5;
   */
  status: OrderStatus;

  /**
   * @generated from field: string created_at = 6;
   */
  createdAt: string;

  constructor(data?: PartialMessage<Order>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "order.Order";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Order;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Order;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Order;

  static equals(a: Order | PlainMessage<Order> | undefined, b: Order | PlainMessage<Order> | undefined): boolean;
}

/**
 * @generated from message order.OrderItem
 */
export declare class OrderItem extends Message<OrderItem> {
  /**
   * @generated from field: string product_id = 1;
   */
  productId: string;

  /**
   * @generated from field: string product_name = 2;
   */
  productName: string;

  /**
   * @generated from field: int32 quantity = 3;
   */
  quantity: number;

  /**
   * @generated from field: double unit_price = 4;
   */
  unitPrice: number;

  constructor(data?: PartialMessage<OrderItem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "order.OrderItem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OrderItem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OrderItem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OrderItem;

  static equals(a: OrderItem | PlainMessage<OrderItem> | undefined, b: OrderItem | PlainMessage<OrderItem> | undefined): boolean;
}

/**
 * @generated from message order.CreateOrderRequest
 */
export declare class CreateOrderRequest extends Message<CreateOrderRequest> {
  /**
   * @generated from field: string customer_id = 1;
   */
  customerId: string;

  /**
   * @generated from field: repeated order.OrderItem items = 2;
   */
  items: OrderItem[];

  constructor(data?: PartialMessage<CreateOrderRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "order.CreateOrderRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateOrderRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateOrderRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateOrderRequest;

  static equals(a: CreateOrderRequest | PlainMessage<CreateOrderRequest> | undefined, b: CreateOrderRequest | PlainMessage<CreateOrderRequest> | undefined): boolean;
}

/**
 * @generated from message order.GetOrderRequest
 */
export declare class GetOrderRequest extends Message<GetOrderRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<GetOrderRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "order.GetOrderRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetOrderRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetOrderRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetOrderRequest;

  static equals(a: GetOrderRequest | PlainMessage<GetOrderRequest> | undefined, b: GetOrderRequest | PlainMessage<GetOrderRequest> | undefined): boolean;
}

