// @generated by protoc-gen-es v1.10.1
// @generated from file order.proto (package order, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum order.OrderStatus
 */
export const OrderStatus = /*@__PURE__*/ proto3.makeEnum(
  "order.OrderStatus",
  [
    {no: 0, name: "ORDER_STATUS_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "ORDER_STATUS_PENDING", localName: "PENDING"},
    {no: 2, name: "ORDER_STATUS_CONFIRMED", localName: "CONFIRMED"},
    {no: 3, name: "ORDER_STATUS_SHIPPED", localName: "SHIPPED"},
    {no: 4, name: "ORDER_STATUS_DELIVERED", localName: "DELIVERED"},
    {no: 5, name: "ORDER_STATUS_CANCELLED", localName: "CANCELLED"},
  ],
);

/**
 * @generated from message order.Order
 */
export const Order = /*@__PURE__*/ proto3.makeMessageType(
  "order.Order",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "items", kind: "message", T: OrderItem, repeated: true },
    { no: 4, name: "total_price", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "status", kind: "enum", T: proto3.getEnumType(OrderStatus) },
    { no: 6, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message order.OrderItem
 */
export const OrderItem = /*@__PURE__*/ proto3.makeMessageType(
  "order.OrderItem",
  () => [
    { no: 1, name: "product_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "product_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "quantity", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "unit_price", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message order.CreateOrderRequest
 */
export const CreateOrderRequest = /*@__PURE__*/ proto3.makeMessageType(
  "order.CreateOrderRequest",
  () => [
    { no: 1, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "items", kind: "message", T: OrderItem, repeated: true },
  ],
);

/**
 * @generated from message order.GetOrderRequest
 */
export const GetOrderRequest = /*@__PURE__*/ proto3.makeMessageType(
  "order.GetOrderRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

