// @generated by protoc-gen-connect-es v1.7.0
// @generated from file order.proto (package order, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateOrderRequest, GetOrderRequest, Order } from "./order_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service order.OrderService
 */
export declare const OrderService: {
  readonly typeName: "order.OrderService",
  readonly methods: {
    /**
     * @generated from rpc order.OrderService.CreateOrder
     */
    readonly createOrder: {
      readonly name: "CreateOrder",
      readonly I: typeof CreateOrderRequest,
      readonly O: typeof Order,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc order.OrderService.GetOrder
     */
    readonly getOrder: {
      readonly name: "GetOrder",
      readonly I: typeof GetOrderRequest,
      readonly O: typeof Order,
      readonly kind: MethodKind.Unary,
    },
  }
};

