// @generated by protoc-gen-connect-es v1.7.0
// @generated from file order.proto (package order, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateOrderRequest, GetOrderRequest, Order } from "./order_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service order.OrderService
 */
export const OrderService = {
  typeName: "order.OrderService",
  methods: {
    /**
     * @generated from rpc order.OrderService.CreateOrder
     */
    createOrder: {
      name: "CreateOrder",
      I: CreateOrderRequest,
      O: Order,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc order.OrderService.GetOrder
     */
    getOrder: {
      name: "GetOrder",
      I: GetOrderRequest,
      O: Order,
      kind: MethodKind.Unary,
    },
  }
};

