// @generated by protoc-gen-es v1.10.1
// @generated from file product.proto (package product, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message product.Product
 */
export declare class Product extends Message<Product> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: double price = 4;
   */
  price: number;

  /**
   * @generated from field: string category_id = 5;
   */
  categoryId: string;

  /**
   * @generated from field: int32 stock = 6;
   */
  stock: number;

  constructor(data?: PartialMessage<Product>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "product.Product";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Product;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Product;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Product;

  static equals(a: Product | PlainMessage<Product> | undefined, b: Product | PlainMessage<Product> | undefined): boolean;
}

/**
 * @generated from message product.ListProductsRequest
 */
export declare class ListProductsRequest extends Message<ListProductsRequest> {
  /**
   * @generated from field: string category_id = 1;
   */
  categoryId: string;

  /**
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;

  constructor(data?: PartialMessage<ListProductsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "product.ListProductsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListProductsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListProductsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListProductsRequest;

  static equals(a: ListProductsRequest | PlainMessage<ListProductsRequest> | undefined, b: ListProductsRequest | PlainMessage<ListProductsRequest> | undefined): boolean;
}

/**
 * @generated from message product.ListProductsResponse
 */
export declare class ListProductsResponse extends Message<ListProductsResponse> {
  /**
   * @generated from field: repeated product.Product products = 1;
   */
  products: Product[];

  /**
   * @generated from field: int32 total_count = 2;
   */
  totalCount: number;

  constructor(data?: PartialMessage<ListProductsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "product.ListProductsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListProductsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListProductsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListProductsResponse;

  static equals(a: ListProductsResponse | PlainMessage<ListProductsResponse> | undefined, b: ListProductsResponse | PlainMessage<ListProductsResponse> | undefined): boolean;
}

/**
 * @generated from message product.GetProductRequest
 */
export declare class GetProductRequest extends Message<GetProductRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<GetProductRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "product.GetProductRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetProductRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetProductRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetProductRequest;

  static equals(a: GetProductRequest | PlainMessage<GetProductRequest> | undefined, b: GetProductRequest | PlainMessage<GetProductRequest> | undefined): boolean;
}

/**
 * @generated from message product.CreateProductRequest
 */
export declare class CreateProductRequest extends Message<CreateProductRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: double price = 3;
   */
  price: number;

  /**
   * @generated from field: string category_id = 4;
   */
  categoryId: string;

  /**
   * @generated from field: int32 stock = 5;
   */
  stock: number;

  constructor(data?: PartialMessage<CreateProductRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "product.CreateProductRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateProductRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateProductRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateProductRequest;

  static equals(a: CreateProductRequest | PlainMessage<CreateProductRequest> | undefined, b: CreateProductRequest | PlainMessage<CreateProductRequest> | undefined): boolean;
}

/**
 * @generated from message product.StreamProductsRequest
 */
export declare class StreamProductsRequest extends Message<StreamProductsRequest> {
  /**
   * @generated from field: string category_id = 1;
   */
  categoryId: string;

  constructor(data?: PartialMessage<StreamProductsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "product.StreamProductsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamProductsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamProductsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamProductsRequest;

  static equals(a: StreamProductsRequest | PlainMessage<StreamProductsRequest> | undefined, b: StreamProductsRequest | PlainMessage<StreamProductsRequest> | undefined): boolean;
}

