// @generated by protoc-gen-connect-es v1.7.0
// @generated from file product.proto (package product, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProductRequest, GetProductRequest, ListProductsRequest, ListProductsResponse, Product, StreamProductsRequest } from "./product_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service product.ProductService
 */
export const ProductService = {
  typeName: "product.ProductService",
  methods: {
    /**
     * @generated from rpc product.ProductService.ListProducts
     */
    listProducts: {
      name: "ListProducts",
      I: ListProductsRequest,
      O: ListProductsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.GetProduct
     */
    getProduct: {
      name: "GetProduct",
      I: GetProductRequest,
      O: Product,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.CreateProduct
     */
    createProduct: {
      name: "CreateProduct",
      I: CreateProductRequest,
      O: Product,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.StreamProducts
     */
    streamProducts: {
      name: "StreamProducts",
      I: StreamProductsRequest,
      O: Product,
      kind: MethodKind.ServerStreaming,
    },
  }
};

