// @generated by protoc-gen-es v1.10.1
// @generated from file product.proto (package product, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message product.Product
 */
export const Product = /*@__PURE__*/ proto3.makeMessageType(
  "product.Product",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "price", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "stock", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message product.ListProductsRequest
 */
export const ListProductsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "product.ListProductsRequest",
  () => [
    { no: 1, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message product.ListProductsResponse
 */
export const ListProductsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "product.ListProductsResponse",
  () => [
    { no: 1, name: "products", kind: "message", T: Product, repeated: true },
    { no: 2, name: "total_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message product.GetProductRequest
 */
export const GetProductRequest = /*@__PURE__*/ proto3.makeMessageType(
  "product.GetProductRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message product.CreateProductRequest
 */
export const CreateProductRequest = /*@__PURE__*/ proto3.makeMessageType(
  "product.CreateProductRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "price", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "stock", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message product.StreamProductsRequest
 */
export const StreamProductsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "product.StreamProductsRequest",
  () => [
    { no: 1, name: "category_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

