// @generated by protoc-gen-connect-es v1.7.0
// @generated from file product.proto (package product, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProductRequest, GetProductRequest, ListProductsRequest, ListProductsResponse, Product, StreamProductsRequest } from "./product_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service product.ProductService
 */
export declare const ProductService: {
  readonly typeName: "product.ProductService",
  readonly methods: {
    /**
     * @generated from rpc product.ProductService.ListProducts
     */
    readonly listProducts: {
      readonly name: "ListProducts",
      readonly I: typeof ListProductsRequest,
      readonly O: typeof ListProductsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.GetProduct
     */
    readonly getProduct: {
      readonly name: "GetProduct",
      readonly I: typeof GetProductRequest,
      readonly O: typeof Product,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.CreateProduct
     */
    readonly createProduct: {
      readonly name: "CreateProduct",
      readonly I: typeof CreateProductRequest,
      readonly O: typeof Product,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.ProductService.StreamProducts
     */
    readonly streamProducts: {
      readonly name: "StreamProducts",
      readonly I: typeof StreamProductsRequest,
      readonly O: typeof Product,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

