global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5000']
    metrics_path: '/metrics'

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:5003']
    metrics_path: '/metrics'

  - job_name: 'envoy'
    static_configs:
      - targets: ['envoy:9901']
    metrics_path: '/stats/prometheus'
