// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260421135557_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Data.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CategoryId = "electronics",
                            Description = "High-performance laptop",
                            Name = "Laptop Pro 15",
                            Price = 2499.9899999999998,
                            Stock = 10
                        },
                        new
                        {
                            Id = "2",
                            CategoryId = "electronics",
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 49.990000000000002,
                            Stock = 100
                        },
                        new
                        {
                            Id = "3",
                            CategoryId = "electronics",
                            Description = "TKL mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 129.99000000000001,
                            Stock = 50
                        },
                        new
                        {
                            Id = "4",
                            CategoryId = "electronics",
                            Description = "7-in-1 USB-C hub",
                            Name = "USB-C Hub",
                            Price = 39.990000000000002,
                            Stock = 200
                        },
                        new
                        {
                            Id = "5",
                            CategoryId = "electronics",
                            Description = "4K IPS display 27 inch",
                            Name = "Monitor 27\"",
                            Price = 599.99000000000001,
                            Stock = 25
                        },
                        new
                        {
                            Id = "6",
                            CategoryId = "electronics",
                            Description = "7.1 surround sound headset",
                            Name = "Gaming Headset",
                            Price = 89.989999999999995,
                            Stock = 75
                        },
                        new
                        {
                            Id = "7",
                            CategoryId = "electronics",
                            Description = "4K UHD webcam with autofocus",
                            Name = "Webcam 4K",
                            Price = 149.99000000000001,
                            Stock = 40
                        },
                        new
                        {
                            Id = "8",
                            CategoryId = "storage",
                            Description = "NVMe PCIe Gen4 SSD",
                            Name = "SSD 1TB",
                            Price = 109.98999999999999,
                            Stock = 150
                        },
                        new
                        {
                            Id = "9",
                            CategoryId = "components",
                            Description = "DDR5 5600MHz dual channel",
                            Name = "RAM 32GB DDR5",
                            Price = 179.99000000000001,
                            Stock = 60
                        },
                        new
                        {
                            Id = "10",
                            CategoryId = "components",
                            Description = "NVIDIA GeForce RTX 4070 12GB",
                            Name = "RTX 4070 GPU",
                            Price = 1299.99,
                            Stock = 15
                        },
                        new
                        {
                            Id = "11",
                            CategoryId = "accessories",
                            Description = "4K 60Hz HDMI 2.1 cable",
                            Name = "HDMI Cable 2m",
                            Price = 12.99,
                            Stock = 500
                        },
                        new
                        {
                            Id = "12",
                            CategoryId = "accessories",
                            Description = "Extended gaming mouse pad",
                            Name = "Mouse Pad XL",
                            Price = 24.989999999999998,
                            Stock = 300
                        },
                        new
                        {
                            Id = "13",
                            CategoryId = "furniture",
                            Description = "Electric height-adjustable desk",
                            Name = "Standing Desk",
                            Price = 499.99000000000001,
                            Stock = 20
                        },
                        new
                        {
                            Id = "14",
                            CategoryId = "furniture",
                            Description = "Ergonomic lumbar support chair",
                            Name = "Office Chair",
                            Price = 349.99000000000001,
                            Stock = 30
                        },
                        new
                        {
                            Id = "15",
                            CategoryId = "audio",
                            Description = "Condenser microphone for streaming",
                            Name = "USB Microphone",
                            Price = 79.989999999999995,
                            Stock = 80
                        },
                        new
                        {
                            Id = "16",
                            CategoryId = "accessories",
                            Description = "Aluminium adjustable laptop stand",
                            Name = "Laptop Stand",
                            Price = 34.990000000000002,
                            Stock = 120
                        },
                        new
                        {
                            Id = "17",
                            CategoryId = "mobile",
                            Description = "PD 65W fast charge power bank",
                            Name = "Power Bank 20000mAh",
                            Price = 59.990000000000002,
                            Stock = 90
                        },
                        new
                        {
                            Id = "18",
                            CategoryId = "networking",
                            Description = "Managed gigabit switch",
                            Name = "Smart Switch 8-port",
                            Price = 89.989999999999995,
                            Stock = 45
                        },
                        new
                        {
                            Id = "19",
                            CategoryId = "electronics",
                            Description = "14-in-1 Thunderbolt 4 docking station",
                            Name = "Thunderbolt 4 Dock",
                            Price = 249.99000000000001,
                            Stock = 35
                        },
                        new
                        {
                            Id = "20",
                            CategoryId = "storage",
                            Description = "USB-C portable SSD 1050 MB/s",
                            Name = "Portable SSD 2TB",
                            Price = 139.99000000000001,
                            Stock = 65
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
