// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260421190135_Seed200Products")]
    partial class Seed200Products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Data.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CategoryId = "electronics",
                            Description = "High-performance laptop",
                            Name = "Laptop Pro 15",
                            Price = 2499.9899999999998,
                            Stock = 10
                        },
                        new
                        {
                            Id = "2",
                            CategoryId = "electronics",
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 49.990000000000002,
                            Stock = 100
                        },
                        new
                        {
                            Id = "3",
                            CategoryId = "electronics",
                            Description = "TKL mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 129.99000000000001,
                            Stock = 50
                        },
                        new
                        {
                            Id = "4",
                            CategoryId = "electronics",
                            Description = "7-in-1 USB-C hub",
                            Name = "USB-C Hub",
                            Price = 39.990000000000002,
                            Stock = 200
                        },
                        new
                        {
                            Id = "5",
                            CategoryId = "electronics",
                            Description = "4K IPS display 27 inch",
                            Name = "Monitor 27\"",
                            Price = 599.99000000000001,
                            Stock = 25
                        },
                        new
                        {
                            Id = "6",
                            CategoryId = "electronics",
                            Description = "7.1 surround sound headset",
                            Name = "Gaming Headset",
                            Price = 89.989999999999995,
                            Stock = 75
                        },
                        new
                        {
                            Id = "7",
                            CategoryId = "electronics",
                            Description = "4K UHD webcam with autofocus",
                            Name = "Webcam 4K",
                            Price = 149.99000000000001,
                            Stock = 40
                        },
                        new
                        {
                            Id = "8",
                            CategoryId = "storage",
                            Description = "NVMe PCIe Gen4 SSD",
                            Name = "SSD 1TB",
                            Price = 109.98999999999999,
                            Stock = 150
                        },
                        new
                        {
                            Id = "9",
                            CategoryId = "components",
                            Description = "DDR5 5600MHz dual channel",
                            Name = "RAM 32GB DDR5",
                            Price = 179.99000000000001,
                            Stock = 60
                        },
                        new
                        {
                            Id = "10",
                            CategoryId = "components",
                            Description = "NVIDIA GeForce RTX 4070 12GB",
                            Name = "RTX 4070 GPU",
                            Price = 1299.99,
                            Stock = 15
                        },
                        new
                        {
                            Id = "11",
                            CategoryId = "accessories",
                            Description = "4K 60Hz HDMI 2.1 cable",
                            Name = "HDMI Cable 2m",
                            Price = 12.99,
                            Stock = 500
                        },
                        new
                        {
                            Id = "12",
                            CategoryId = "accessories",
                            Description = "Extended gaming mouse pad",
                            Name = "Mouse Pad XL",
                            Price = 24.989999999999998,
                            Stock = 300
                        },
                        new
                        {
                            Id = "13",
                            CategoryId = "furniture",
                            Description = "Electric height-adjustable desk",
                            Name = "Standing Desk",
                            Price = 499.99000000000001,
                            Stock = 20
                        },
                        new
                        {
                            Id = "14",
                            CategoryId = "furniture",
                            Description = "Ergonomic lumbar support chair",
                            Name = "Office Chair",
                            Price = 349.99000000000001,
                            Stock = 30
                        },
                        new
                        {
                            Id = "15",
                            CategoryId = "audio",
                            Description = "Condenser microphone for streaming",
                            Name = "USB Microphone",
                            Price = 79.989999999999995,
                            Stock = 80
                        },
                        new
                        {
                            Id = "16",
                            CategoryId = "accessories",
                            Description = "Aluminium adjustable laptop stand",
                            Name = "Laptop Stand",
                            Price = 34.990000000000002,
                            Stock = 120
                        },
                        new
                        {
                            Id = "17",
                            CategoryId = "mobile",
                            Description = "PD 65W fast charge power bank",
                            Name = "Power Bank 20000mAh",
                            Price = 59.990000000000002,
                            Stock = 90
                        },
                        new
                        {
                            Id = "18",
                            CategoryId = "networking",
                            Description = "Managed gigabit switch",
                            Name = "Smart Switch 8-port",
                            Price = 89.989999999999995,
                            Stock = 45
                        },
                        new
                        {
                            Id = "19",
                            CategoryId = "electronics",
                            Description = "14-in-1 Thunderbolt 4 docking station",
                            Name = "Thunderbolt 4 Dock",
                            Price = 249.99000000000001,
                            Stock = 35
                        },
                        new
                        {
                            Id = "20",
                            CategoryId = "storage",
                            Description = "USB-C portable SSD 1050 MB/s",
                            Name = "Portable SSD 2TB",
                            Price = 139.99000000000001,
                            Stock = 65
                        },
                        new
                        {
                            Id = "21",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 1",
                            Price = 63.990000000000002,
                            Stock = 10
                        },
                        new
                        {
                            Id = "22",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 1GB",
                            Price = 17.989999999999998,
                            Stock = 17
                        },
                        new
                        {
                            Id = "23",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 1m",
                            Price = 14.99,
                            Stock = 24
                        },
                        new
                        {
                            Id = "24",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 1GbE",
                            Price = 32.990000000000002,
                            Stock = 31
                        },
                        new
                        {
                            Id = "25",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 1",
                            Price = 29.989999999999998,
                            Stock = 38
                        },
                        new
                        {
                            Id = "26",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 1",
                            Price = 3.9900000000000002,
                            Stock = 45
                        },
                        new
                        {
                            Id = "27",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 1",
                            Price = 8.9900000000000002,
                            Stock = 52
                        },
                        new
                        {
                            Id = "28",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 1GB",
                            Price = 49.990000000000002,
                            Stock = 59
                        },
                        new
                        {
                            Id = "29",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 1GB",
                            Price = 98.989999999999995,
                            Stock = 66
                        },
                        new
                        {
                            Id = "30",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 1W",
                            Price = 41.990000000000002,
                            Stock = 73
                        },
                        new
                        {
                            Id = "31",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 1",
                            Price = 15.99,
                            Stock = 80
                        },
                        new
                        {
                            Id = "32",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 1W",
                            Price = 22.489999999999998,
                            Stock = 87
                        },
                        new
                        {
                            Id = "33",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 1",
                            Price = 14.99,
                            Stock = 94
                        },
                        new
                        {
                            Id = "34",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 1",
                            Price = 14.289999999999999,
                            Stock = 101
                        },
                        new
                        {
                            Id = "35",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat1",
                            Price = 10.789999999999999,
                            Stock = 108
                        },
                        new
                        {
                            Id = "36",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 1",
                            Price = 31.989999999999998,
                            Stock = 115
                        },
                        new
                        {
                            Id = "37",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 1",
                            Price = 8.9900000000000002,
                            Stock = 122
                        },
                        new
                        {
                            Id = "38",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 1",
                            Price = 59.990000000000002,
                            Stock = 129
                        },
                        new
                        {
                            Id = "39",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 2",
                            Price = 87.989999999999995,
                            Stock = 136
                        },
                        new
                        {
                            Id = "40",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 2GB",
                            Price = 23.989999999999998,
                            Stock = 143
                        },
                        new
                        {
                            Id = "41",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 2m",
                            Price = 11.99,
                            Stock = 150
                        },
                        new
                        {
                            Id = "42",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 2GbE",
                            Price = 26.989999999999998,
                            Stock = 157
                        },
                        new
                        {
                            Id = "43",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 2",
                            Price = 24.989999999999998,
                            Stock = 164
                        },
                        new
                        {
                            Id = "44",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 2",
                            Price = 5.4900000000000002,
                            Stock = 171
                        },
                        new
                        {
                            Id = "45",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 2",
                            Price = 11.99,
                            Stock = 178
                        },
                        new
                        {
                            Id = "46",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 2GB",
                            Price = 39.990000000000002,
                            Stock = 185
                        },
                        new
                        {
                            Id = "47",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 2GB",
                            Price = 80.989999999999995,
                            Stock = 192
                        },
                        new
                        {
                            Id = "48",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 2W",
                            Price = 34.990000000000002,
                            Stock = 199
                        },
                        new
                        {
                            Id = "49",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 2",
                            Price = 21.989999999999998,
                            Stock = 206
                        },
                        new
                        {
                            Id = "50",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 2W",
                            Price = 29.989999999999998,
                            Stock = 13
                        },
                        new
                        {
                            Id = "51",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 2",
                            Price = 11.99,
                            Stock = 20
                        },
                        new
                        {
                            Id = "52",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 2",
                            Price = 11.69,
                            Stock = 27
                        },
                        new
                        {
                            Id = "53",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat2",
                            Price = 8.9900000000000002,
                            Stock = 34
                        },
                        new
                        {
                            Id = "54",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 2",
                            Price = 43.990000000000002,
                            Stock = 41
                        },
                        new
                        {
                            Id = "55",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 2",
                            Price = 11.99,
                            Stock = 48
                        },
                        new
                        {
                            Id = "56",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 2",
                            Price = 47.990000000000002,
                            Stock = 55
                        },
                        new
                        {
                            Id = "57",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 3",
                            Price = 71.989999999999995,
                            Stock = 62
                        },
                        new
                        {
                            Id = "58",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 3GB",
                            Price = 19.989999999999998,
                            Stock = 69
                        },
                        new
                        {
                            Id = "59",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 3m",
                            Price = 16.489999999999998,
                            Stock = 76
                        },
                        new
                        {
                            Id = "60",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 3GbE",
                            Price = 35.990000000000002,
                            Stock = 83
                        },
                        new
                        {
                            Id = "61",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 3",
                            Price = 19.989999999999998,
                            Stock = 90
                        },
                        new
                        {
                            Id = "62",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 3",
                            Price = 4.4900000000000002,
                            Stock = 97
                        },
                        new
                        {
                            Id = "63",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 3",
                            Price = 9.9900000000000002,
                            Stock = 104
                        },
                        new
                        {
                            Id = "64",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 3GB",
                            Price = 54.990000000000002,
                            Stock = 111
                        },
                        new
                        {
                            Id = "65",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 3GB",
                            Price = 107.98999999999999,
                            Stock = 118
                        },
                        new
                        {
                            Id = "66",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 3W",
                            Price = 27.989999999999998,
                            Stock = 125
                        },
                        new
                        {
                            Id = "67",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 3",
                            Price = 17.989999999999998,
                            Stock = 132
                        },
                        new
                        {
                            Id = "68",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 3W",
                            Price = 24.989999999999998,
                            Stock = 139
                        },
                        new
                        {
                            Id = "69",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 3",
                            Price = 16.489999999999998,
                            Stock = 146
                        },
                        new
                        {
                            Id = "70",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 3",
                            Price = 15.59,
                            Stock = 153
                        },
                        new
                        {
                            Id = "71",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat3",
                            Price = 7.1900000000000004,
                            Stock = 160
                        },
                        new
                        {
                            Id = "72",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 3",
                            Price = 35.990000000000002,
                            Stock = 167
                        },
                        new
                        {
                            Id = "73",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 3",
                            Price = 9.9900000000000002,
                            Stock = 174
                        },
                        new
                        {
                            Id = "74",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 3",
                            Price = 65.989999999999995,
                            Stock = 181
                        },
                        new
                        {
                            Id = "75",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 4",
                            Price = 95.989999999999995,
                            Stock = 188
                        },
                        new
                        {
                            Id = "76",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 4GB",
                            Price = 15.99,
                            Stock = 195
                        },
                        new
                        {
                            Id = "77",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 4m",
                            Price = 13.49,
                            Stock = 202
                        },
                        new
                        {
                            Id = "78",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 4GbE",
                            Price = 29.989999999999998,
                            Stock = 209
                        },
                        new
                        {
                            Id = "79",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 4",
                            Price = 27.489999999999998,
                            Stock = 16
                        },
                        new
                        {
                            Id = "80",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 4",
                            Price = 5.9900000000000002,
                            Stock = 23
                        },
                        new
                        {
                            Id = "81",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 4",
                            Price = 7.9900000000000002,
                            Stock = 30
                        },
                        new
                        {
                            Id = "82",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 4GB",
                            Price = 44.990000000000002,
                            Stock = 37
                        },
                        new
                        {
                            Id = "83",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 4GB",
                            Price = 89.989999999999995,
                            Stock = 44
                        },
                        new
                        {
                            Id = "84",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 4W",
                            Price = 38.490000000000002,
                            Stock = 51
                        },
                        new
                        {
                            Id = "85",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 4",
                            Price = 23.989999999999998,
                            Stock = 58
                        },
                        new
                        {
                            Id = "86",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 4W",
                            Price = 19.989999999999998,
                            Stock = 65
                        },
                        new
                        {
                            Id = "87",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 4",
                            Price = 13.49,
                            Stock = 72
                        },
                        new
                        {
                            Id = "88",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 4",
                            Price = 12.99,
                            Stock = 79
                        },
                        new
                        {
                            Id = "89",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat4",
                            Price = 9.8900000000000006,
                            Stock = 86
                        },
                        new
                        {
                            Id = "90",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 4",
                            Price = 47.990000000000002,
                            Stock = 93
                        },
                        new
                        {
                            Id = "91",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 4",
                            Price = 7.9900000000000002,
                            Stock = 100
                        },
                        new
                        {
                            Id = "92",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 4",
                            Price = 53.990000000000002,
                            Stock = 107
                        },
                        new
                        {
                            Id = "93",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 5",
                            Price = 79.989999999999995,
                            Stock = 114
                        },
                        new
                        {
                            Id = "94",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 5GB",
                            Price = 21.989999999999998,
                            Stock = 121
                        },
                        new
                        {
                            Id = "95",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 5m",
                            Price = 17.989999999999998,
                            Stock = 128
                        },
                        new
                        {
                            Id = "96",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 5GbE",
                            Price = 23.989999999999998,
                            Stock = 135
                        },
                        new
                        {
                            Id = "97",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 5",
                            Price = 22.489999999999998,
                            Stock = 142
                        },
                        new
                        {
                            Id = "98",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 5",
                            Price = 4.9900000000000002,
                            Stock = 149
                        },
                        new
                        {
                            Id = "99",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 5",
                            Price = 10.99,
                            Stock = 156
                        },
                        new
                        {
                            Id = "100",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 5GB",
                            Price = 59.990000000000002,
                            Stock = 163
                        },
                        new
                        {
                            Id = "101",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 5GB",
                            Price = 71.989999999999995,
                            Stock = 170
                        },
                        new
                        {
                            Id = "102",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 5W",
                            Price = 31.489999999999998,
                            Stock = 177
                        },
                        new
                        {
                            Id = "103",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 5",
                            Price = 19.989999999999998,
                            Stock = 184
                        },
                        new
                        {
                            Id = "104",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 5W",
                            Price = 27.489999999999998,
                            Stock = 191
                        },
                        new
                        {
                            Id = "105",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 5",
                            Price = 17.989999999999998,
                            Stock = 198
                        },
                        new
                        {
                            Id = "106",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 5",
                            Price = 10.390000000000001,
                            Stock = 205
                        },
                        new
                        {
                            Id = "107",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat5",
                            Price = 8.0899999999999999,
                            Stock = 12
                        },
                        new
                        {
                            Id = "108",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 5",
                            Price = 39.990000000000002,
                            Stock = 19
                        },
                        new
                        {
                            Id = "109",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 5",
                            Price = 10.99,
                            Stock = 26
                        },
                        new
                        {
                            Id = "110",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 5",
                            Price = 71.989999999999995,
                            Stock = 33
                        },
                        new
                        {
                            Id = "111",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 6",
                            Price = 63.990000000000002,
                            Stock = 40
                        },
                        new
                        {
                            Id = "112",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 6GB",
                            Price = 17.989999999999998,
                            Stock = 47
                        },
                        new
                        {
                            Id = "113",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 6m",
                            Price = 14.99,
                            Stock = 54
                        },
                        new
                        {
                            Id = "114",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 6GbE",
                            Price = 32.990000000000002,
                            Stock = 61
                        },
                        new
                        {
                            Id = "115",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 6",
                            Price = 29.989999999999998,
                            Stock = 68
                        },
                        new
                        {
                            Id = "116",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 6",
                            Price = 3.9900000000000002,
                            Stock = 75
                        },
                        new
                        {
                            Id = "117",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 6",
                            Price = 8.9900000000000002,
                            Stock = 82
                        },
                        new
                        {
                            Id = "118",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 6GB",
                            Price = 49.990000000000002,
                            Stock = 89
                        },
                        new
                        {
                            Id = "119",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 6GB",
                            Price = 98.989999999999995,
                            Stock = 96
                        },
                        new
                        {
                            Id = "120",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 6W",
                            Price = 41.990000000000002,
                            Stock = 103
                        },
                        new
                        {
                            Id = "121",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 6",
                            Price = 15.99,
                            Stock = 110
                        },
                        new
                        {
                            Id = "122",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 6W",
                            Price = 22.489999999999998,
                            Stock = 117
                        },
                        new
                        {
                            Id = "123",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 6",
                            Price = 14.99,
                            Stock = 124
                        },
                        new
                        {
                            Id = "124",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 6",
                            Price = 14.289999999999999,
                            Stock = 131
                        },
                        new
                        {
                            Id = "125",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat6",
                            Price = 10.789999999999999,
                            Stock = 138
                        },
                        new
                        {
                            Id = "126",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 6",
                            Price = 31.989999999999998,
                            Stock = 145
                        },
                        new
                        {
                            Id = "127",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 6",
                            Price = 8.9900000000000002,
                            Stock = 152
                        },
                        new
                        {
                            Id = "128",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 6",
                            Price = 59.990000000000002,
                            Stock = 159
                        },
                        new
                        {
                            Id = "129",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 7",
                            Price = 87.989999999999995,
                            Stock = 166
                        },
                        new
                        {
                            Id = "130",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 7GB",
                            Price = 23.989999999999998,
                            Stock = 173
                        },
                        new
                        {
                            Id = "131",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 7m",
                            Price = 11.99,
                            Stock = 180
                        },
                        new
                        {
                            Id = "132",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 7GbE",
                            Price = 26.989999999999998,
                            Stock = 187
                        },
                        new
                        {
                            Id = "133",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 7",
                            Price = 24.989999999999998,
                            Stock = 194
                        },
                        new
                        {
                            Id = "134",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 7",
                            Price = 5.4900000000000002,
                            Stock = 201
                        },
                        new
                        {
                            Id = "135",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 7",
                            Price = 11.99,
                            Stock = 208
                        },
                        new
                        {
                            Id = "136",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 7GB",
                            Price = 39.990000000000002,
                            Stock = 15
                        },
                        new
                        {
                            Id = "137",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 7GB",
                            Price = 80.989999999999995,
                            Stock = 22
                        },
                        new
                        {
                            Id = "138",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 7W",
                            Price = 34.990000000000002,
                            Stock = 29
                        },
                        new
                        {
                            Id = "139",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 7",
                            Price = 21.989999999999998,
                            Stock = 36
                        },
                        new
                        {
                            Id = "140",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 7W",
                            Price = 29.989999999999998,
                            Stock = 43
                        },
                        new
                        {
                            Id = "141",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 7",
                            Price = 11.99,
                            Stock = 50
                        },
                        new
                        {
                            Id = "142",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 7",
                            Price = 11.69,
                            Stock = 57
                        },
                        new
                        {
                            Id = "143",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat7",
                            Price = 8.9900000000000002,
                            Stock = 64
                        },
                        new
                        {
                            Id = "144",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 7",
                            Price = 43.990000000000002,
                            Stock = 71
                        },
                        new
                        {
                            Id = "145",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 7",
                            Price = 11.99,
                            Stock = 78
                        },
                        new
                        {
                            Id = "146",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 7",
                            Price = 47.990000000000002,
                            Stock = 85
                        },
                        new
                        {
                            Id = "147",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 8",
                            Price = 71.989999999999995,
                            Stock = 92
                        },
                        new
                        {
                            Id = "148",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 8GB",
                            Price = 19.989999999999998,
                            Stock = 99
                        },
                        new
                        {
                            Id = "149",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 8m",
                            Price = 16.489999999999998,
                            Stock = 106
                        },
                        new
                        {
                            Id = "150",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 8GbE",
                            Price = 35.990000000000002,
                            Stock = 113
                        },
                        new
                        {
                            Id = "151",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 8",
                            Price = 19.989999999999998,
                            Stock = 120
                        },
                        new
                        {
                            Id = "152",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 8",
                            Price = 4.4900000000000002,
                            Stock = 127
                        },
                        new
                        {
                            Id = "153",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 8",
                            Price = 9.9900000000000002,
                            Stock = 134
                        },
                        new
                        {
                            Id = "154",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 8GB",
                            Price = 54.990000000000002,
                            Stock = 141
                        },
                        new
                        {
                            Id = "155",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 8GB",
                            Price = 107.98999999999999,
                            Stock = 148
                        },
                        new
                        {
                            Id = "156",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 8W",
                            Price = 27.989999999999998,
                            Stock = 155
                        },
                        new
                        {
                            Id = "157",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 8",
                            Price = 17.989999999999998,
                            Stock = 162
                        },
                        new
                        {
                            Id = "158",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 8W",
                            Price = 24.989999999999998,
                            Stock = 169
                        },
                        new
                        {
                            Id = "159",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 8",
                            Price = 16.489999999999998,
                            Stock = 176
                        },
                        new
                        {
                            Id = "160",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 8",
                            Price = 15.59,
                            Stock = 183
                        },
                        new
                        {
                            Id = "161",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat8",
                            Price = 7.1900000000000004,
                            Stock = 190
                        },
                        new
                        {
                            Id = "162",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 8",
                            Price = 35.990000000000002,
                            Stock = 197
                        },
                        new
                        {
                            Id = "163",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 8",
                            Price = 9.9900000000000002,
                            Stock = 204
                        },
                        new
                        {
                            Id = "164",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 8",
                            Price = 65.989999999999995,
                            Stock = 11
                        },
                        new
                        {
                            Id = "165",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 9",
                            Price = 95.989999999999995,
                            Stock = 18
                        },
                        new
                        {
                            Id = "166",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 9GB",
                            Price = 15.99,
                            Stock = 25
                        },
                        new
                        {
                            Id = "167",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 9m",
                            Price = 13.49,
                            Stock = 32
                        },
                        new
                        {
                            Id = "168",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 9GbE",
                            Price = 29.989999999999998,
                            Stock = 39
                        },
                        new
                        {
                            Id = "169",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 9",
                            Price = 27.489999999999998,
                            Stock = 46
                        },
                        new
                        {
                            Id = "170",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 9",
                            Price = 5.9900000000000002,
                            Stock = 53
                        },
                        new
                        {
                            Id = "171",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 9",
                            Price = 7.9900000000000002,
                            Stock = 60
                        },
                        new
                        {
                            Id = "172",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 9GB",
                            Price = 44.990000000000002,
                            Stock = 67
                        },
                        new
                        {
                            Id = "173",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 9GB",
                            Price = 89.989999999999995,
                            Stock = 74
                        },
                        new
                        {
                            Id = "174",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 9W",
                            Price = 38.490000000000002,
                            Stock = 81
                        },
                        new
                        {
                            Id = "175",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 9",
                            Price = 23.989999999999998,
                            Stock = 88
                        },
                        new
                        {
                            Id = "176",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 9W",
                            Price = 19.989999999999998,
                            Stock = 95
                        },
                        new
                        {
                            Id = "177",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 9",
                            Price = 13.49,
                            Stock = 102
                        },
                        new
                        {
                            Id = "178",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 9",
                            Price = 12.99,
                            Stock = 109
                        },
                        new
                        {
                            Id = "179",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat9",
                            Price = 9.8900000000000006,
                            Stock = 116
                        },
                        new
                        {
                            Id = "180",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 9",
                            Price = 47.990000000000002,
                            Stock = 123
                        },
                        new
                        {
                            Id = "181",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 9",
                            Price = 7.9900000000000002,
                            Stock = 130
                        },
                        new
                        {
                            Id = "182",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 9",
                            Price = 53.990000000000002,
                            Stock = 137
                        },
                        new
                        {
                            Id = "183",
                            CategoryId = "audio",
                            Description = "Bluetooth 5.3 earbuds with ANC",
                            Name = "Wireless Earbuds 10",
                            Price = 79.989999999999995,
                            Stock = 144
                        },
                        new
                        {
                            Id = "184",
                            CategoryId = "storage",
                            Description = "USB 3.2 Gen2 flash drive",
                            Name = "USB Flash Drive 10GB",
                            Price = 21.989999999999998,
                            Stock = 151
                        },
                        new
                        {
                            Id = "185",
                            CategoryId = "accessories",
                            Description = "DP 1.4 HBR3 cable",
                            Name = "DisplayPort Cable 10m",
                            Price = 17.989999999999998,
                            Stock = 158
                        },
                        new
                        {
                            Id = "186",
                            CategoryId = "networking",
                            Description = "PCIe network interface card",
                            Name = "Network Card 10GbE",
                            Price = 23.989999999999998,
                            Stock = 165
                        },
                        new
                        {
                            Id = "187",
                            CategoryId = "accessories",
                            Description = "Laptop cooling pad with fans",
                            Name = "Cooling Pad 10",
                            Price = 22.489999999999998,
                            Stock = 172
                        },
                        new
                        {
                            Id = "188",
                            CategoryId = "accessories",
                            Description = "Privacy slide cover for webcam",
                            Name = "Webcam Cover 10",
                            Price = 4.9900000000000002,
                            Stock = 179
                        },
                        new
                        {
                            Id = "189",
                            CategoryId = "accessories",
                            Description = "USB-C to USB-A adapter",
                            Name = "Type-C Adapter 10",
                            Price = 10.99,
                            Stock = 186
                        },
                        new
                        {
                            Id = "190",
                            CategoryId = "components",
                            Description = "DDR4 3200MHz memory module",
                            Name = "DDR4 RAM 10GB",
                            Price = 59.990000000000002,
                            Stock = 193
                        },
                        new
                        {
                            Id = "191",
                            CategoryId = "storage",
                            Description = "NVMe M.2 2280 SSD",
                            Name = "PCIe SSD 10GB",
                            Price = 71.989999999999995,
                            Stock = 200
                        },
                        new
                        {
                            Id = "192",
                            CategoryId = "furniture",
                            Description = "LED desk lamp with dimmer",
                            Name = "Desk Lamp 10W",
                            Price = 31.489999999999998,
                            Stock = 207
                        },
                        new
                        {
                            Id = "193",
                            CategoryId = "accessories",
                            Description = "Under-desk cable organizer",
                            Name = "Cable Management Kit 10",
                            Price = 19.989999999999998,
                            Stock = 14
                        },
                        new
                        {
                            Id = "194",
                            CategoryId = "mobile",
                            Description = "Qi wireless charging pad",
                            Name = "Wireless Charger 10W",
                            Price = 27.489999999999998,
                            Stock = 21
                        },
                        new
                        {
                            Id = "195",
                            CategoryId = "mobile",
                            Description = "Adjustable phone holder",
                            Name = "Phone Stand 10",
                            Price = 17.989999999999998,
                            Stock = 28
                        },
                        new
                        {
                            Id = "196",
                            CategoryId = "networking",
                            Description = "WiFi smart plug with timer",
                            Name = "Smart Plug 10",
                            Price = 10.390000000000001,
                            Stock = 35
                        },
                        new
                        {
                            Id = "197",
                            CategoryId = "networking",
                            Description = "Shielded ethernet cable 3m",
                            Name = "Ethernet Cable Cat10",
                            Price = 8.0899999999999999,
                            Stock = 42
                        },
                        new
                        {
                            Id = "198",
                            CategoryId = "audio",
                            Description = "Portable Bluetooth speaker",
                            Name = "Mini Speaker 10",
                            Price = 39.990000000000002,
                            Stock = 49
                        },
                        new
                        {
                            Id = "199",
                            CategoryId = "mobile",
                            Description = "Tempered glass screen protector",
                            Name = "Screen Protector 10",
                            Price = 10.99,
                            Stock = 56
                        },
                        new
                        {
                            Id = "200",
                            CategoryId = "peripherals",
                            Description = "Graphics drawing tablet USB",
                            Name = "Drawing Tablet 10",
                            Price = 71.989999999999995,
                            Stock = 63
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
